package com.awaion.demo008.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.9
 * Generated source version: 3.0.9
 */
@WebService(targetNamespace = "https://cxf.apache.org/", name = "ICalculateService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ICalculateService {

    @WebResult(name = "return", targetNamespace = "https://cxf.apache.org/", partName = "return")
    @WebMethod
    public int sum(
            @WebParam(partName = "arg0", name = "arg0")
                    int arg0,
            @WebParam(partName = "arg1", name = "arg1")
                    int arg1
    );
}
