server:
  port: 80

#
springdoc:
  api-docs:
    enabled: true # 启用接口文档

#
knife4j:
  enable: true # 开启增强模式

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo004?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



