server:
  port: 10013

spring:
  application:
    name: alibaba-service3
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true